### PR TITLE
fix_MediaCatalog

### PR DESCRIPTION
**Pull request by Happy-come-come**
The MediaCatalog.json has been changed to MediaCatalog.bytes and has been serialized using MemoryPack.
Therefore, a .NET program was created to deserialize it using MemoryPack, enabling us to retrieve files from MediaResources again using this program.

### CODE REVIEW

**Comment by ArkanDash** [comment]
> The MediaCatalog.json has been changed to MediaCatalog.bytes and has been serialized using MemoryPack. Therefore, a .NET program was created to deserialize it using MemoryPack, enabling us to retrieve files from MediaResources again using this program.

Also add .NET Core 8.0 as an requirement to get the MemoryPack to work.

**Comment by Happy-come-come** [comment]
Ok. I did it.

**Comment by Happy-come-come** [comment]
Maybe I should do a more detailed case separation, because at the moment there are only x86_64 windows and linux (glibc only) versions of the executable to deserialize Memorypack. Would it be better to do so? Or should I put in the notes that only those are supported?

**Comment by fiseleo** [comment]
Well, I'm very sorry to see this so late. I have completed a new downloader over there.

**Pull request merged**
